//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t2s.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class container
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public container()
        {
            this.idContainerMovimentacao = new HashSet<movimentacao>();
        }

        [Key]
        public int idContainer { get; set; }
        [Required]
        [Display(Name = "Cliente")]
        public int idCliente { get; set; }
        [Required]
        [Display(Name = "Número do Container")]
        [StringLength(11)]
        [RegularExpression("^[A-Z]{4}[0-9]{7}$", ErrorMessage = "Formato do nome do container inválido. Exemplo: AAAA01234567.")]
        public string nmNumeroCntr { get; set; }
        [Required]
        [Display(Name = "Tipo")]
        public int idTipo { get; set; }
        [Required]
        [Display(Name = "Status")]
        public int idStatus { get; set; }
        [Required]
        [Display(Name = "Categoria")]
        public int idCategoria { get; set; }

        public virtual cliente idClienteContainer { get; set; }
        public virtual status idCategoriaContainer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimentacao> idContainerMovimentacao { get; set; }
        public virtual status idStatusContainer { get; set; }
        public virtual status idTipoContainer { get; set; }
    }
}
