//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t2s.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class movimentacao
    {
        [Key]
        public int idMovimentacao { get; set; }
        [Required]
        [Display(Name = "Container")]
        public int idContainer { get; set; }
        [Required]
        [Display(Name = "Navio")]
        public int idNavio { get; set; }
        [Required]
        [Display(Name = "Tipo de Movimentação")]
        public int idTipoMovimentacao { get; set; }
        [Required]
        [Display(Name = "Data de Início")]
        public System.DateTime dtInicio { get; set; }
        [Required]
        [Display(Name = "Data de Fim")]
        public System.DateTime dtFim { get; set; }

        public virtual container idContainerMovimentacao { get; set; }
        public virtual status idStatusTipoMovimentacao { get; set; }
        public virtual navio idNavioMovimentacao { get; set; }
    }
}
