//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t2s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class navio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public navio()
        {
            this.idNavioMovimentacao = new HashSet<movimentacao>();
        }
    
        public int idNavio { get; set; }
        public string nmNavio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<movimentacao> idNavioMovimentacao { get; set; }
    }
}
