//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t2s.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class t2sEntities2 : DbContext
    {
        public t2sEntities2()
            : base("name=t2sEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<container> container { get; set; }
        public virtual DbSet<movimentacao> movimentacao { get; set; }
        public virtual DbSet<navio> navio { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<vwMovimentacoes> vwMovimentacoes { get; set; }
    }
}
