//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace t2s.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMovimentacoes
    {
        public string cliente { get; set; }
        public string tipoMovimentacao { get; set; }
        public Nullable<int> qtdeMovimentacoes { get; set; }
    }
}
